### PR TITLE
Dev 1.0.0 bug fixes

### PR DESCRIPTION
**Pull request by CS76**
Fixed a bunch of issues, the NEM Account services are working fine now. 
Transaction model needs more work. Hopefully, this helps :)
Let me know your testing strategy. Will update the unit tests soon.

### CODE REVIEW

**Comment by evias** [comment]
lol sorry, its the first time I ever merge something entirely using Github xD .. I think i am gonna stick to my little terminal, thanks a lot for your contribution !

**Comment by evias** [comment]
do you have a NEM address ?

**Comment by CS76** [comment]
NDIL2WTRBR7FAOK6OT67N6GOO4GABYMONVBFSQW5

**Comment by CS76** [comment]
Thank you 👍

**Pull request merged**
